- name: Just do nothing and wait
  hosts: myhosts
  tasks:
   - name: Pause
     ansible.builtin.pause:
        minutes: 1

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world
